data:
  name: 'DR2D-PDEBench'
  train:
    name: 'DR2D-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/DiffusionReaction/PDEBench/npz/train'
    n_all_samples: 10
    reduced_resolution: 4
    reduced_resolution_t: 10
    real_space_range: [-1, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 50
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  val:
    name: 'DR2D-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/DiffusionReaction/PDEBench/npz/test'
    n_all_samples: 10
    reduced_resolution: 4
    reduced_resolution_t: 10
    real_space_range: [-1, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 50
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  test:
    name: 'DR2D-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/DiffusionReaction/PDEBench/npz/test'
    n_all_samples: 10
    reduced_resolution: 4
    reduced_resolution_t: 10
    real_space_range: [-1, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 50
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]

model:
  branch_layers: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 100]
  trunk_layers: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
  activation: tanh

train:
  batchsize: 4
  epochs: 2000
  milestones: [400, 800, 1200]
  base_lr: 0.001
  scheduler_gamma: 0.5
  save_dir: 'DeepONet-DR2D-PDEBench-debug'
  save_name: 'DeepONet-DR2D-PDEBench-debug.pt'
  save_epoch: 1
  eval_epoch: 1

log:
  logdir: 'DeepONet-DR2D-PDEBench-debug'
  entity: jiahaohuang
  project: PhysGTN-DR
  wandb_mode: offline
  name: DeepONet-DR2D-PDEBench-debug