data:
  name: 'CFD2Da-PDEBench'
  train:
    name: 'CFD2Da-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/CompressibleNavierStokes/CompressibleNavierStokes2D/PDEBench/npz/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train/train'
    n_all_samples: 10
    reduced_resolution: 4
    reduced_resolution_t: 2
    real_space_range: [0, 1]
    real_time_range: [0, 1]
    in_seq: 1
    out_seq: 10
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  val:
    name: 'CFD2Da-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/CompressibleNavierStokes/CompressibleNavierStokes2D/PDEBench/npz/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train/test'
    n_all_samples: 10
    reduced_resolution: 4
    reduced_resolution_t: 2
    real_space_range: [0, 1]
    real_time_range: [0, 1]
    in_seq: 1
    out_seq: 10
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  test:
    name: 'CFD2Da-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/CompressibleNavierStokes/CompressibleNavierStokes2D/PDEBench/npz/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train/test'
    n_all_samples: 10
    reduced_resolution: 4
    reduced_resolution_t: 2
    real_space_range: [0, 1]
    real_time_range: [0, 1]
    in_seq: 1
    out_seq: 10
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]

model:
  branch_layers: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 100]
  trunk_layers: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
  activation: tanh

train:
  batchsize: 4
  epochs: 2000
  milestones: [400, 800, 1200]
  base_lr: 0.001
  scheduler_gamma: 0.5
  save_dir: weights/CFD2D/DeepONet/DeepONet-CFD2Da-PDEBench-debug
  save_name: 'DeepONet-CFD2Da-PDEBench-debug.pt'
  save_epoch: 1
  eval_epoch: 1

log:
  logdir: weights/CFD2D/DeepONet/DeepONet-CFD2Da-PDEBench-debug
  entity: jiahaohuang
  project: PhysGTN-CFD
  wandb_mode: offline
  name: DeepONet-CFD2Da-PDEBench-debug