data:
  name: 'SW2D-PDEBench'
  train:
    name: 'SW2D-PDEBench'
    dataset_path: '/media/NAS07/USER_PATH/jh/PDE/data/ShallowWater/PDEBench/npz/train'
    n_all_samples: 900
    reduced_resolution: 1
    reduced_resolution_t: 1
    real_space_range: [-0.25, 0.25]
    real_time_range: [0, 1]
    in_seq: 10
    out_seq: 91
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  val:
    name: 'SW2D-PDEBench'
    dataset_path: '/media/NAS07/USER_PATH/jh/PDE/data/ShallowWater/PDEBench/npz/test'
    n_all_samples: 100
    reduced_resolution: 1
    reduced_resolution_t: 1
    real_space_range: [-0.25, 0.25]
    real_time_range: [0, 1]
    in_seq: 10
    out_seq: 91
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  test:
    name: 'SW2D-PDEBench'
    dataset_path: '/media/NAS07/USER_PATH/jh/PDE/data/ShallowWater/PDEBench/npz/test'
    weight_path: '/media/NAS06/jiahao/Mamba_Transformer_PDE/DeepONet/SW2D/DeepONet-SW2D-PDEBench-Dx1-Tx1-MSE/DeepONet-SW2D-PDEBench-Dx1-Tx1-MSE_1000.pt'
    n_all_samples: 100
    reduced_resolution: 1
    reduced_resolution_t: 1
    real_space_range: [-0.25, 0.25]
    real_time_range: [0, 1]
    in_seq: 10
    out_seq: 91
    metrics_list: ["RMSE", "nRMSE", "Rel_L2_Norm"]

model:
  branch_layers: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
  trunk_layers: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
  activation: tanh

train:
  batchsize: 8
  epochs: 2000
  milestones: [400, 800, 1200]
  base_lr: 0.001
  scheduler_gamma: 0.5
  save_dir: '/home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/results_comparison/SW2D/DeepONet-SW2D-PDEBench-Dx1-Tx1-MSE/'
  save_name: 'DeepONet-SW2D-PDEBench-Dx1-Tx1-MSE.pt'
  save_epoch: 100
  eval_epoch: 100

log:
  logdir: '/home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/results_comparison/SW2D/DeepONet-SW2D-PDEBench-Dx1-Tx1-MSE'
  entity: jiahaohuang
  project: DeepONet
  wandb_mode: online
  name: DeepONet-SW2D-PDEBench-Dx1-Tx1-MSE