data:
  name: 'IncomNS2D-PDEBench'
  train:
    name: 'IncomNS2D-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/IncompressibleNavierStokes/IncompressibleNavierStokes2D/PDEBench/npz/train'
    n_all_samples: 16
    reduced_resolution: 8
    reduced_resolution_t: 20
    real_space_range: [0, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 49
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  val:
    name: 'IncomNS2D-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/IncompressibleNavierStokes/IncompressibleNavierStokes2D/PDEBench/npz/test'
    n_all_samples: 4
    reduced_resolution: 8
    reduced_resolution_t: 20
    real_space_range: [0, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 49
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  test:
    name: 'IncomNS2D-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/IncompressibleNavierStokes/IncompressibleNavierStokes2D/PDEBench/npz/test'
    n_all_samples: 4
    reduced_resolution: 8
    reduced_resolution_t: 20
    real_space_range: [0, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 49
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]

model:
  branch_layers: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 100]
  trunk_layers: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
  activation: tanh

train:
  batchsize: 2
  epochs: 2000
  milestones: [400, 800, 1200]
  base_lr: 0.001
  scheduler_gamma: 0.5
  save_dir: 'DeepONet-IncomNS2D-PDEBench-debug'
  save_name: 'DeepONet-IncomNS2D-PDEBench-debug.pt'
  save_epoch: 1
  eval_epoch: 1

log:
  logdir: DeepONet-IncomNS2D-PDEBench-debug
  entity: jiahaohuang
  project: DeepONet-NS
  wandb_mode: offline
  name: DeepONet-IncomNS2D-PDEBench-debug