data:
  name: 'IncomNS2D-PDEBench'
  train:
    name: 'IncomNS2D-PDEBench'
    dataset_path: '/home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/physics_graph_transformer/data/IncompressibleNavierStokes/IncompressibleNavierStokes2D/PDEBench/npz/train'
    n_all_samples: 892
    reduced_resolution: 8
    reduced_resolution_t: 50
    real_space_range: [0, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 19
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  val:
    name: 'IncomNS2D-PDEBench'
    dataset_path: '/home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/physics_graph_transformer/data/IncompressibleNavierStokes/IncompressibleNavierStokes2D/PDEBench/npz/test'
    n_all_samples: 100
    reduced_resolution: 8
    reduced_resolution_t: 50
    real_space_range: [0, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 19
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  test:
    name: 'IncomNS2D-PDEBench'
    dataset_path: '/home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/physics_graph_transformer/data/IncompressibleNavierStokes/IncompressibleNavierStokes2D/PDEBench/npz/test'
    n_all_samples: 100
    reduced_resolution: 8
    reduced_resolution_t: 50
    real_space_range: [0, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 19
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]

model:
  branch_layers: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 100]
  trunk_layers: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
  activation: tanh

train:
  batchsize: 8
  epochs: 2000
  milestones: [400, 800, 1200]
  base_lr: 0.001
  scheduler_gamma: 0.5
  save_dir: '/home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/results_comparison/IncomNS2D/DeepONet/DeepONet-IncomNS2D-PDEBench-Dx8-Tx50'
  save_name: 'DeepONet-IncomNS2D-PDEBench-Dx8-Tx50.pt'
  save_epoch: 100
  eval_epoch: 1

log:
  logdir: /home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/results_comparison/IncomNS2D/DeepONet/DeepONet-IncomNS2D-PDEBench-Dx8-Tx50
  entity: jiahaohuang
  project: DeepONet-NS
  wandb_mode: online
  name: DeepONet-IncomNS2D-PDEBench-Dx8-Tx50