data:
  name: 'Darcy'
  path: '/media/ssd/data_temp/PDE/data/DarcyFlow/Caltech/raw/Darcy_421/piececonst_r421_N1024_smooth1.mat'
  total_num: 1024
  offset: 0
  n_sample: 1000
  nx: 421
  sub: 7
  pde_sub: 2
  metrics_list: ["MSE", "RMSE", "nRMSE", "Max", "Rel_L2_Norm"]

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [20, 20, 20, 20]
  modes2: [20, 20, 20, 20]
  fc_dim: 128
  act: gelu
  pad_ratio: [0., 0.]

train:
  batchsize: 20
  num_iter: 60_001
  milestones: [5_000, 7_500, 10_000, 15_000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  f_loss: 0.0
  xy_loss: 5.0
  save_step: 500000
  eval_step: 1_000

test:
  path: '/media/ssd/data_temp/PDE/data/DarcyFlow/Caltech/raw/Darcy_421/piececonst_r421_N1024_smooth2.mat'
  total_num: 1024
  offset: 0
  n_sample: 500
  nx: 421
  sub: 2
  batchsize: 1
  
  
log:
  logdir: PINO-DarcyFlow-Caltech-beta1.0-D5
  entity: jiahaohuang
  project: PINO-DF-Caltech
  wandb_mode: online


