data:
  train:
    name: 'DarcyFlow-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/DarcyFlow/PDEBench/2D_DarcyFlow_beta1.0_Train/train'
    n_all_samples: 9000
    reduced_resolution: 8
    reduced_resolution_pde: 4
    real_space_range: "1"
    beta: 1.0
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max", "Rel_L2_Norm"]
  val:
    name: 'DarcyFlow-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/DarcyFlow/PDEBench/2D_DarcyFlow_beta1.0_Train/test'
    n_all_samples: 1000
    reduced_resolution: 2
    real_space_range: "1"
    beta: 1.0
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max", "Rel_L2_Norm"]
  test:
    name: 'DarcyFlow-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/DarcyFlow/PDEBench/2D_DarcyFlow_beta1.0_Train/test'
    n_all_samples: 1000
    reduced_resolution: 2
    real_space_range: "1"
    beta: 1.0
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max", "Rel_L2_Norm"]
model:
  layers: [64, 64, 64, 64, 64]
  modes1: [20, 20, 20, 20]
  modes2: [20, 20, 20, 20]
  fc_dim: 128
  act: gelu
  pad_ratio: 0.7

train:
  batchsize: 20
  num_iter: 30_001
  milestones: [5_000, 7_500, 10_000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  f_loss: 0.005
  xy_loss: 5.0
  save_step: 5000000
  eval_step: 1_000

log:
  logdir: PINO-DarcyFlow-PDEBench-beta1.0-D5F0.005-LR-D8P4E2-MSE
  entity: jiahaohuang
  project: PINO-DF
  wandb_mode: online


