data:
  train:
    name: 'DR2D-PDEBench'
    dataset_path: '/home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/physics_graph_transformer/data/DiffusionReaction/PDEBench/npz/train'
    n_all_samples: 900
    reduced_resolution: 2
    reduced_resolution_t: 2
    real_space_range: [-1, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 50
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  val:
    name: 'DR2D-PDEBench'
    dataset_path: '/home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/physics_graph_transformer/data/DiffusionReaction/PDEBench/npz/test'
    n_all_samples: 100
    reduced_resolution: 2
    reduced_resolution_t: 2
    real_space_range: [-1, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 50
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  test:
    name: 'DR2D-PDEBench'
    dataset_path: '/home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/physics_graph_transformer/data/DiffusionReaction/PDEBench/npz/test'
    n_all_samples: 100
    reduced_resolution: 2
    reduced_resolution_t: 2
    real_space_range: [-1, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 50
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  modes3: [12, 12, 12, 12]
  fc_dim: 128
  act: gelu
  pad_ratio: [0.0, 0.125]
  in_dim: 5
  out_dim: 2

train:
  batchsize: 8
  num_iter: 200_001
  milestones: [20_000, 60_000, 120_000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 10.0
  save_step: 5000
  eval_step: 1

log:
  logdir: /home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/results_comparison/IncomNS2D/FNO/FNO-DR2D-PDEBench-Dx2-Tx2
  entity: jiahaohuang
  project: PINO-DR
  wandb_mode: online
  name: FNO-DR-PDEBench-Dx2-Tx2