data:
  train:
    name: 'DR2D-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/DiffusionReaction/PDEBench/npz/train'
    n_all_samples: 10
    reduced_resolution: 4
    reduced_resolution_t: 10
    real_space_range: [-1, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 50
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  val:
    name: 'DR2D-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/DiffusionReaction/PDEBench/npz/test'
    n_all_samples: 10
    reduced_resolution: 4
    reduced_resolution_t: 10
    real_space_range: [-1, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 50
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  test:
    name: 'DR2D-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/DiffusionReaction/PDEBench/npz/test'
    n_all_samples: 10
    reduced_resolution: 4
    reduced_resolution_t: 10
    real_space_range: [-1, 1]
    real_time_range: [0, 5]
    in_seq: 1
    out_seq: 50
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  modes3: [12, 12, 12, 12]
  fc_dim: 128
  act: gelu
  pad_ratio: [0.0, 0.125]
  in_dim: 5
  out_dim: 2

train:
  batchsize: 4
  num_iter: 200_001
  milestones: [20_000, 60_000, 120_000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 10.0
  save_step: 10
  eval_step: 1

log:
  logdir: FNO-DR2D-PDEBench-debug
  entity: jiahaohuang
  project: PINO-DR
  wandb_mode: offline
  name: FNO-DR2D-PDEBench-debug