data:
  train:
    name: 'CFD2Da-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/CompressibleNavierStokes/CompressibleNavierStokes2D/PDEBench/npz/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train/train'
    n_all_samples: 10
    reduced_resolution: 4
    reduced_resolution_t: 2
    real_space_range: [0, 1]
    real_time_range: [0, 1]
    in_seq: 1
    out_seq: 10
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  val:
    name: 'CFD2Da-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/CompressibleNavierStokes/CompressibleNavierStokes2D/PDEBench/npz/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train/test'
    n_all_samples: 10
    reduced_resolution: 4
    reduced_resolution_t: 2
    real_space_range: [0, 1]
    real_time_range: [0, 1]
    in_seq: 1
    out_seq: 10
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  test:
    name: 'CFD2Da-PDEBench'
    dataset_path: '/media/ssd/data_temp/PDE/data/CompressibleNavierStokes/CompressibleNavierStokes2D/PDEBench/npz/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train/test'
    n_all_samples: 10
    reduced_resolution: 4
    reduced_resolution_t: 2
    real_space_range: [0, 1]
    real_time_range: [0, 1]
    in_seq: 1
    out_seq: 10
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  modes3: [12, 12, 12, 12]
  fc_dim: 128
  act: gelu
  pad_ratio: [0.0, 0.125]
  in_dim: 7
  out_dim: 2

train:
  batchsize: 4
  num_iter: 200_001
  milestones: [20_000, 60_000, 120_000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 10.0
  save_step: 10
  eval_step: 1

log:
  logdir: weights/CFD2D/FNO/FNO-CFD2Da-PDEBench-debug
  entity: jiahaohuang
  project: PhysGTN-CFD
  wandb_mode: offline
  name: FNO-CFD2Da-PDEBench-debug