data:
  train:
    name: 'SW2D-PDEBench'
    dataset_path: '/home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/physics_graph_transformer/data/ShallowWater/PDEBench/npz/train'
    n_all_samples: 900
    reduced_resolution: 1
    reduced_resolution_t: 1
    real_space_range: [-0.25, 0.25]
    real_time_range: [0, 1]
    in_seq: 10
    out_seq: 91
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  val:
    name: 'SW2D-PDEBench'
    dataset_path: '/home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/physics_graph_transformer/data/ShallowWater/PDEBench/npz/test'
    n_all_samples: 100
    reduced_resolution: 1
    reduced_resolution_t: 1
    real_space_range: [-0.25, 0.25]
    real_time_range: [0, 1]
    in_seq: 10
    out_seq: 91
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]
  test:
    name: 'SW2D-PDEBench'
    dataset_path: '/home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/physics_graph_transformer/data/ShallowWater/PDEBench/npz/test'
    n_all_samples: 100
    reduced_resolution: 1
    reduced_resolution_t: 1
    real_space_range: [-0.25, 0.25]
    real_time_range: [0, 1]
    in_seq: 10
    out_seq: 91
    metrics_list: ["MSE", "RMSE", "nRMSE", "Max"]

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  modes3: [12, 12, 12, 12]
  fc_dim: 128
  act: gelu
  pad_ratio: [0.0, 0.125]
  in_dim: 13
  out_dim: 1

train:
  batchsize: 8
  num_iter: 200_001
  milestones: [20_000, 60_000, 120_000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  save_step: 5000
  eval_step: 1
  use_mse_loss: True

log:
  logdir: /home/jh2446/rds/rds-ai323-trafficcam/physics_graph_transformer/results_comparison/SW2D/FNO/FNO-SW2D-PDEBench-Dx1-Tx1-MSE
  entity: jiahaohuang
  project: PhysGTN-SW
  wandb_mode: online
  name: FNO-SW2D-PDEBench-Dx1-Tx1-MSE